# Generated by Django 6.0.5 on 2026-05-07 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('mensaje_nuevo', 'Mensaje nuevo'), ('pedido_confirmado', 'Pedido confirmado'), ('pedido_en_preparacion', 'Pedido en preparación'), ('pedido_en_camino', 'Pedido en camino'), ('pedido_entregado', 'Pedido entregado'), ('pedido_cancelado', 'Pedido cancelado'), ('negociacion_aceptada', 'Negociación aceptada'), ('negociacion_cancelada', 'Negociación cancelada'), ('calificacion_recibida', 'Calificación recibida')], max_length=30)),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('leida', models.BooleanField(default=False)),
                ('leida_en', models.DateTimeField(blank=True, null=True)),
                ('url_destino', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'db_table': 'notificacion',
                'ordering': ['-created_at'],
            },
        ),
    ]
