# Generated by Django 6.0.5 on 2026-05-07 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.PositiveSmallIntegerField(help_text='Puntuación del 1 al 5')),
                ('comentario', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Calificación',
                'verbose_name_plural': 'Calificaciones',
                'db_table': 'calificacion',
            },
        ),
        migrations.CreateModel(
            name='HistorialEstadoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('confirmado', 'Confirmado'), ('en_preparacion', 'En preparación'), ('en_camino', 'En camino'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], max_length=15)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Historial de estado de pedido',
                'verbose_name_plural': 'Historial de estados de pedidos',
                'db_table': 'historial_estado_pedido',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_acordada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_acordado', models.DecimalField(decimal_places=2, help_text='Precio unitario acordado en pesos colombianos', max_digits=10)),
                ('precio_total', models.DecimalField(decimal_places=2, help_text='cantidad_acordada * precio_acordado', max_digits=12)),
                ('estado_actual', models.CharField(choices=[('confirmado', 'Confirmado'), ('en_preparacion', 'En preparación'), ('en_camino', 'En camino'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='confirmado', max_length=15)),
                ('direccion_entrega', models.CharField(blank=True, max_length=500, null=True)),
                ('notas_entrega', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'db_table': 'pedido',
                'ordering': ['-created_at'],
            },
        ),
    ]
