# Generated by Django 6.0.5 on 2026-05-07 00:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('negociacion', '0002_initial'),
        ('pedidos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacion',
            name='calificado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_recibidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='calificador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_emitidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historialestadopedido',
            name='registrado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estados_registrados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pedido',
            name='negociacion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='pedido', to='negociacion.negociacion'),
        ),
        migrations.AddField(
            model_name='historialestadopedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_estados', to='pedidos.pedido'),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='pedidos.pedido'),
        ),
        migrations.AlterUniqueTogether(
            name='calificacion',
            unique_together={('pedido', 'calificador')},
        ),
    ]
