# Generated by Django 6.0.5 on 2026-06-04 00:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispositivoConfiable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_agent', models.TextField()),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('navegador', models.CharField(blank=True, max_length=50, null=True)),
                ('sistema_operativo', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('ultimo_acceso', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos_confiables', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dispositivo Confiable',
                'verbose_name_plural': 'Dispositivos Confiables',
                'db_table': 'dispositivo_confiable',
                'unique_together': {('usuario', 'user_agent')},
            },
        ),
    ]
