# Generated by Django 6.0.5 on 2026-05-07 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('icono', models.CharField(blank=True, help_text='Nombre del icono para mostrar en la interfaz', max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Categoría de producto',
                'verbose_name_plural': 'Categorías de productos',
                'db_table': 'categoria_producto',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='FotoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_cloudinary', models.URLField(max_length=500)),
                ('public_id_cloudinary', models.CharField(max_length=255)),
                ('es_principal', models.BooleanField(default=False)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Foto de producto',
                'verbose_name_plural': 'Fotos de productos',
                'db_table': 'foto_producto',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, help_text='Precio en pesos colombianos', max_digits=10)),
                ('cantidad_disponible', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidad_medida', models.CharField(choices=[('kg', 'Kilogramo'), ('lb', 'Libra'), ('und', 'Unidad'), ('bulto', 'Bulto'), ('lt', 'Litro'), ('arroba', 'Arroba')], default='kg', max_length=10)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('agotado', 'Agotado'), ('inactivo', 'Inactivo')], default='activo', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='productos.categoriaproducto')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'producto',
                'ordering': ['-created_at'],
            },
        ),
    ]
