# Generated by Django 6.0.5 on 2026-06-04 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negociacion', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='correo_recordatorio_enviado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='negociacion',
            name='estado',
            field=models.CharField(choices=[('abierta', 'Abierta'), ('pedido_creado', 'Pedido Creado'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], default='abierta', max_length=20),
        ),
    ]
